blank_issues_enabled: true
contact_links:
  - name: ðŸ’¬ Questions & Discussions
    url: https://github.com/lrivallain/az-mapping/discussions
    about: Ask questions or start a discussion instead of opening an issue.
